spring:
  application:
    name: ms-articulos
  datasource:
    url: ${ARTICULOS_DB_URL:jdbc:postgresql://localhost:5432/bodega_articulos}
    username: ${ARTICULOS_DB_USERNAME:postgres}
    password: ${ARTICULOS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${ARTICULOS_PORT:8082}
